# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Work.delete_all
Post.delete_all
Work.create(name: "Dice World", 
            description: "Dice World was an experiment in randomization
                         algorithms. On scene was made with a point that generates rooms
                         at different positions. that spawned a room at different areas, then I moved on
                         to perlin noise algorithms and eventually made a rudementary
                         minecraft clone based on planet mars.",
            github_url: "https://github.com/deathtenk/dice-world",
            image_url: "http://i.imgur.com/IWppGjs.png")
Work.create(name: "Alphastore",
            description: "Alphastore was an application made as a final project
                          for Betamore Academy. It features a front page, a cart,
                          and a working checkout. It demonstrates competency in 
                          rails development.",
            github_url: "https://github.com/deathtenk/alphastore",
            image_url: "http://e27.co/wp-content/uploads/2013/08/e-commerce_header.jpg")
Work.create(name: "Fly",
            description: "Fly is an open-source flight simulator written in Unity using Mono through .NET that
                          sends data about the planes position to a server. It was made to demonstrate
                          the scalability and flexibility of Tin Can's xAPI.",
            github_url: "https://github.com/deathtenk/fly",
            image_url: "http://i.imgur.com/OIoUhqM.jpg")
Work.create(name: "Dwarf Statements",
            description: "Dwarf Statements is a clojure application that parses XML files generated by Dwarf
                          Fortress. The idea was to groom the data that Dwarf Fortress generates to get a better
                          idea of the worlds made by the games detailed randomization algorithms.",
            github_url: "https://github.com/yetanalytics/dwarf_statements",
            image_url: "http://fs01.androidpit.info/afg/x42/3755342-1352343666304.jpg")
Work.create(name: "Friendbook",
            description: "Friendbook is another application written for betamore that demonstrates rails relationships.
                          Friends are capable of having other friends, posts are shared on the front page. This is
                          still a work in progress. ",
            github_url:"https://github.com/deathtenk/friendbook",
            image_url: "http://www.dogster.com/files/fields/puppy-names-3.jpg")


Post.create(title: "No Posts yet!",
            body: "Don't worry, they're coming! :D")